### ISSUE TITLE
Minions not showing up in Details

### ISSUE THREAD

**Issue by dnotari** [latenighttales/alcali#161]
So I got Alcali working almost completely.  It looks as though even though I have 150ish minions in my master, I can only see a max of 25 minions in the details.

I can see all the keys in the guy and can select all my servers as targets but I have not had luck getting them in the details area.  I have tried refreshing them on that screen no luck.

Was wondering if there is anything I may need to do to try to get it to see all my minions.

**Comment by mattLLVW** [comment]
Hey @dnotari thanks for trying Alcali.

Are you talking about [this](https://alcali.dev/views/minions/) view?

For Alcali to add minions in db, the user logged in Alcali and configured in the external_auth must have the right to run `pillar.items` and `grain.items` on the minion you want to add. It could be that.

**Comment by agreenbhm** [comment]
I'm experiencing the same problem. @mattLLVW, would you please post an example of the external_auth configuration that should be set?

**Comment by mattLLVW** [comment]
Hey @agreenbhm, there's an exemple in the [docs](https://alcali.dev/installation/).
There's also the [salt docs](https://docs.saltstack.com/en/latest/topics/eauth/index.html) for more infos.

**Comment by agreenbhm** [comment]
I've got everything set exactly like in the examples, but can't see the minions.  Should the "admin" user in the example docs have access to that?

**Comment by mattLLVW** [comment]
@agreenbhm please create another issue and describe exactly what is your problem. Thanks!

**Comment by dnotari** [comment]
@mattLLVW,

Yes this is the view.  

We followed the guide and are using the Rest endpoint authentication.  Maybe tokens is a better way to authenticate?  Not sure if you have any seen any issues one way versus the other.

-Dan

**Comment by mattLLVW** [comment]
@dnotari using my answer from another issue:

>why would I use the alcali auth vs the rest auth?

the alcali auth use a custom auth module (so it's a bit troublesome to install) to authenticate users but the master does not need to be able to talk to alcali.

On the other hand the rest auth is easier to use but password are validated using an endpoint on Alcali so the master must be able to talk to Alcali and you must ensure that Alcali is running in https so that passwords does not transit in clear.

I don't think that's the problem.

Have you set the salt master in debug mode? anything show up in the logs?

You could also try setting the environ variable `DJANGO_DEBUG=true` in your Alcali env file but please make sure that alcali is not exposed while doing so because it will [leak important informations](https://docs.djangoproject.com/en/3.0/ref/settings/#debug).

**Comment by anitakrueger** [comment]
I'm seeing the exact same issue as @dnotari now. I've got 249 accepted keys of minions, but only 16 minions on the Minions view with none of them showing details.

Unfortunately setting `DJANGO_DEBUG=true` in the .env file hasn't helped to produce debug output, however starting gunicorn with `--log-level debug` looks to produce debug output.

I don't see any errors in the salt master log.

The alcali debug logs now show this when trying to refresh all the minions:
```
Feb 13 04:49:52 ip-10-3-2-225 alcali: [2020-02-13 04:49:52 -0600] [32207] [DEBUG] 10 workers
Feb 13 04:50:44 ip-10-3-2-225 alcali: [2020-02-13 04:50:44 -0600] [32218] [DEBUG] POST /api/token/refresh/
Feb 13 04:50:44 ip-10-3-2-225 alcali: [2020-02-13 04:50:44 -0600] [32218] [DEBUG] POST /api/minions/refresh_minions/
Feb 13 04:50:44 ip-10-3-2-225 alcali: [2020-02-13 04:50:44 -0600] [32222] [DEBUG] POST /api/token/verify/
Feb 13 04:50:46 ip-10-3-2-225 alcali: [2020-02-13 04:50:46 -0600] [32226] [DEBUG] POST /api/token/verify/
Feb 13 04:50:49 ip-10-3-2-225 alcali: [2020-02-13 04:50:49 -0600] [32220] [DEBUG] POST /api/token/verify/
Feb 13 04:50:50 ip-10-3-2-225 alcali: [2020-02-13 04:50:50 -0600] [32220] [DEBUG] POST /api/token/verify/
Feb 13 04:50:52 ip-10-3-2-225 alcali: [2020-02-13 04:50:52 -0600] [32217] [DEBUG] POST /api/token/verify/
Feb 13 04:50:54 ip-10-3-2-225 alcali: [2020-02-13 04:50:54 -0600] [32217] [DEBUG] POST /api/token/verify/
Feb 13 04:50:57 ip-10-3-2-225 alcali: [2020-02-13 04:50:57 -0600] [32217] [DEBUG] POST /api/token/verify/
Feb 13 04:50:59 ip-10-3-2-225 alcali: [2020-02-13 04:50:59 -0600] [32220] [DEBUG] POST /api/token/verify/
Feb 13 04:51:00 ip-10-3-2-225 alcali: [2020-02-13 04:51:00 -0600] [32224] [DEBUG] POST /api/token/verify/
Feb 13 04:51:02 ip-10-3-2-225 alcali: [2020-02-13 04:51:02 -0600] [32216] [DEBUG] POST /api/token/verify/
Feb 13 04:51:04 ip-10-3-2-225 alcali: [2020-02-13 04:51:04 -0600] [32211] [DEBUG] POST /api/token/verify/
Feb 13 04:51:06 ip-10-3-2-225 alcali: [2020-02-13 04:51:06 -0600] [32226] [DEBUG] POST /api/token/verify/
Feb 13 04:51:08 ip-10-3-2-225 alcali: [2020-02-13 04:51:08 -0600] [32222] [DEBUG] POST /api/token/verify/
Feb 13 04:51:10 ip-10-3-2-225 alcali: [2020-02-13 04:51:10 -0600] [32222] [DEBUG] POST /api/token/verify/
Feb 13 04:51:12 ip-10-3-2-225 alcali: [2020-02-13 04:51:12 -0600] [32210] [DEBUG] POST /api/token/verify/
Feb 13 04:51:13 ip-10-3-2-225 alcali: [2020-02-13 04:51:13 -0600] [32222] [DEBUG] POST /api/token/verify/
Feb 13 04:51:15 ip-10-3-2-225 alcali: [2020-02-13 04:51:15 -0600] [32207] [CRITICAL] WORKER TIMEOUT (pid:32218)
Feb 13 04:51:15 ip-10-3-2-225 alcali: [2020-02-13 04:51:15 -0600] [32218] [INFO] Worker exiting (pid: 32218)
Feb 13 04:51:15 ip-10-3-2-225 alcali: [2020-02-13 04:51:15 -0600] [32217] [DEBUG] GET /502.html
Feb 13 04:51:15 ip-10-3-2-225 alcali: Not Found: /502.html
Feb 13 04:51:15 ip-10-3-2-225 alcali: [2020-02-13 04:51:15 -0600] [32462] [INFO] Booting worker with pid: 32462
```

When trying to get details for a minion, I see the following in the debug output:
```
Feb 13 04:52:29 ip-10-3-2-225 alcali: [2020-02-13 04:52:29 -0600] [32222] [DEBUG] GET /api/minions/dev-elasticsearch-03/
Feb 13 04:52:29 ip-10-3-2-225 alcali: Not Found: /api/minions/dev-elasticsearch-03/
```

I'm using REST auth and my user has the following privs:
```
      - .*
      - '@runner'
      - '@wheel'
```

**Comment by dnotari** [comment]
@mattLLVW hey Matt, I do see similar errors to @anitakrueger reported above.  We are going to look at our salt server and check some of the REST API timeouts, seems that might be root cause.  I will report back if we find anything that helps solves this problem.

**Comment by anitakrueger** [comment]
Just wanted to mention that we have actually set `expire_responses=False` and a rest_timeout of 600 in the salt master configuration. We've had those in there for a long time, because we're calling the salt-api to kick off relatively long running orchestrations.

As I said, I actually see 0 errors in the salt master log when trying to refresh the minions. It's like it's not doing all of the ones that are found in the accepted keys or maybe just does them in batches and then at some point stops?

Also, could it have something to do with the `[CRITICAL] WORKER TIMEOUT (pid:32218)` and the worker being killed off?

**Comment by mattLLVW** [comment]
@anitakrueger @dnotari definitely looks like a gunicorn issue.
see:

> Feb 13 04:50:44 ip-10-3-2-225 alcali: [2020-02-13 04:50:44 -0600] [32218] [DEBUG] POST /api/token/refresh/
> ...
> Feb 13 04:51:15 ip-10-3-2-225 alcali: [2020-02-13 04:51:15 -0600] [32207] [CRITICAL] WORKER TIMEOUT (pid:32218)

30sc : default gunicorn timeout.

please [try increasing it](https://docs.gunicorn.org/en/stable/settings.html#timeout).

**Comment by anitakrueger** [comment]
Definitely something funky going on with the gunicorn workers. I increased the timeout to 120 and it got more of the minions connected, but even though for 44 of them, the pillar.items and grains.items call succeeded (I can see that in the jobs view), the minion detail doesn't show up.

Does the app actually use more than 3 workers? I've set this to 10 now and it only seem to make a difference for refreshing the minion keys.

And one more question please: what else apart from running pillar.items and grains.items is needed for the minion to show its detailed view?

Thanks a lot Matt!

**Comment by mattLLVW** [comment]
@anitakrueger configuring Gunicorn is a bit tricky but you shouldn't need a lot of workers, see [this](https://docs.gunicorn.org/en/stable/design.html#how-many-workers)(`(2 x $num_cores) + 1`). 

Alcali loops on every accepted keys in db(the [keys view](https://alcali.dev/views/keys/)) and run `pillar.items` and then `grain.items`.
It's definitely not efficient.. and because you have "a lot"  of minions, it could take a lot more than 120 sc (depending on your connection etc..), so i would increase it even more and check.

> And one more question please: what else apart from running pillar.items and grains.items is needed for the minion to show its detailed view?

Nothing if you didn't set any [minion fields](https://alcali.dev/views/settings/#minions-fields)

I don't get what's the issue with the minion details though, could you check what's happening in your web browser console? Any error?

**Comment by anitakrueger** [comment]
Ok, so I've reduced the number of workers back to 3 and set the timeout to 600. That made it discover 217 of my 249 minions ;)

I've then experimented with the gevent worker-class and that seems to work better in this case, because it uses the async workers that won't get killed. With that and kicking off the minion refresh again, it discovered all my 249 minions. Yay!


Now with regards to the details view. I just see a blank page when clicking on any of them. The developer console in the browser shows a 404:
```
VM44:1 GET https://saltserver/api/minions/dev-cassandra-01/ 404 (Not Found)
(anonymous) @ VM44:1
(anonymous) @ xhr.js:172
e.exports @ xhr.js:11
e.exports @ dispatchRequest.js:59
Promise.then (async)
l.request @ Axios.js:53
n.forEach.l.<computed> @ Axios.js:68
(anonymous) @ bind.js:9
loadData @ MinionDetail.vue:64
mounted @ MinionDetail.vue:60
it @ vue.runtime.esm.js:1854
ji @ vue.runtime.esm.js:4213
insert @ vue.runtime.esm.js:3139
it @ vue.runtime.esm.js:1854
i @ vue.runtime.esm.js:2175
A @ vue.runtime.esm.js:6340
(anonymous) @ vue.runtime.esm.js:6559
Oi.e._update @ vue.runtime.esm.js:3942
n @ vue.runtime.esm.js:4060
tn.get @ vue.runtime.esm.js:4473
tn.run @ vue.runtime.esm.js:4548
Gi @ vue.runtime.esm.js:4304
(anonymous) @ vue.runtime.esm.js:1980
ut @ vue.runtime.esm.js:1906
Promise.then (async)
st @ vue.runtime.esm.js:1933
pt @ vue.runtime.esm.js:1990
Qi @ vue.runtime.esm.js:4396
tn.update @ vue.runtime.esm.js:4538
Oi.e.$forceUpdate @ vue.runtime.esm.js:3963
(anonymous) @ vue.runtime.esm.js:8194
l @ vue.runtime.esm.js:2235
it @ vue.runtime.esm.js:1854
i @ vue.runtime.esm.js:2175
(anonymous) @ vue.runtime.esm.js:7690
(anonymous) @ vue.runtime.esm.js:336
u @ vue.runtime.esm.js:7390
c @ vue.runtime.esm.js:7395
createError.js:16 Uncaught (in promise) Error: Request failed with status code 404
    at e.exports (createError.js:16)
    at e.exports (settle.js:17)
    at XMLHttpRequest.d.onreadystatechange (xhr.js:59)
```

My js is very rusty, I'm afraid.

The debug log from gunicorn just shows the get request being made:
```
Feb 13 16:59:06 ip-10-3-2-225 alcali: [2020-02-13 16:59:06 -0600] [26822] [DEBUG] GET /api/minions/dev-cassandra-01/
```

I do see the entries for pillar and grains in the database for all the minions, so that can't be the issue. May be I'm missing something else.
I'll debug more tomorrow.

Thanks a lot for all your help thus far! I'm loving the ui :)

**Comment by mattLLVW** [comment]
Alright, figured it out.
https://github.com/latenighttales/alcali/issues/138 :man_facepalming: 
@anitakrueger @dnotari you probably installed from Pypi or docker, and your minions most likely have characters that do not match `[0-9a-zA-Z.]+`. this is fixed on develop and a new version should have been released. my bad.

**Comment by dnotari** [comment]
@mattLLVW ok I see what you mean yeah our naming convention is along the same lines as Anita (ex vmre-mngo-d001.domain).  We haven't tried the timeout yet but we will see if we can get an updated build installed instead.  We may not have time before the weekend but next week for sure.

I appreciate the help, so far we liking the tool and the UI.  I will update and close the ticket hopefully in the coming days.

**Comment by anitakrueger** [comment]
@mattLLVW that looks better ;) I can't install from develop, but made the change manually on our system. Any chance you could make another release please?

Thanks a bunch for figuring this out!

**Comment by mattLLVW** [comment]
@dnotari @anitakrueger Alcali 2019.2.4 and 2018.3.4 released :tada:

**Comment by anitakrueger** [comment]
Splendid, thank you.

**Comment by dnotari** [comment]
@mattLLVW we did a quick update and with a few tweaks to the gunicorn settings looks like things are syncing as expected.  I think we are good.
